/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>
/* The shift and conversion this generator relies on are implementation-defined in C11 --
 * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.
 * Two's complement itself is the language's own rule and needs no probe. */
_Static_assert((-1 >> 1) == -1, "arithmetic right shift");
_Static_assert((int)0xFFFFFFFFu == -1, "modular conversion");

/* Proved under the following assumptions (SYNTAX.md 12).
 * Each is a statement about the MACHINE that this program takes on
 * trust. A falsifier names the probe that could refute it.
 *   treffer_suche_endet (assume): falsifier sonde_treffer_suche
 */

#define DROP 0u

#define NIMM_AN 1u

#define FREI 0u

#define BESTEHEND 2u

#define KEIN_TREFFER 256u

uint32_t entpacke(uint32_t laenge);

uint32_t gib_kopf_proto(void);

uint32_t gib_kopf_quelle(void);

uint32_t gib_kopf_ziel(void);

uint32_t gib_kopf_qport(void);

uint32_t gib_kopf_zport(void);

uint32_t gib_kopf_flaggen(void);

uint32_t passt(uint32_t r, uint32_t proto, uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t flaggen);

uint32_t entscheide_regeln(uint32_t proto, uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t flaggen);

void VSPERRE_nimm(void);
void VSPERRE_gib(void);

uint32_t suche_oder_lege_an(uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t iprot, uint32_t flaggen, uint32_t jetzt);

void zaehle_urteil(uint32_t u);

void zaehle_regel(uint32_t r);

void zaehle_fehl(void);

void zaehle_voll(void);

_Atomic uint32_t UHR_TICK;

static uint32_t tick(void) __attribute__((unused));

static bool sonde_treffer_suche(void) __attribute__((const)) __attribute__((unused));

_Noreturn void treffer_aufgegeben(void);

static uint32_t treffer_index(uint32_t proto, uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t flaggen) __attribute__((unused));

static uint32_t zaehle_weiter(uint32_t u) __attribute__((unused));

uint32_t entscheide(uint32_t laenge, uint32_t faden);

static uint32_t tick(void) {
    uint32_t t = atomic_load_explicit(&UHR_TICK, memory_order_relaxed);
    if (t < 4294967295u) {
        /* publishes { nothing } -- paired at compile time (V001-V004) */
        atomic_store_explicit(&UHR_TICK, t + 1, memory_order_relaxed);
    }
    uint32_t frisch = atomic_load_explicit(&UHR_TICK, memory_order_relaxed);
    return frisch;
}

static bool sonde_treffer_suche(void) {
    return true;
}

static uint32_t treffer_index(uint32_t proto, uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t flaggen) {
    uint32_t k = 0;
    uint32_t antwort = KEIN_TREFFER;
    /* forever suche -- `per_pass … ops` is a claim about ONE pass, and the cost
     * pass has already checked it (W6). Nothing counts here at run time, so
     * `on_exceeded` gets no branch -- it gets the line below instead, which makes
     * the C compiler read the clause a second time.
     * `progress treffer_suche_endet` is an assumption about the WORLD; nothing static
     * establishes it, and `treffer_aufgegeben` is its falsifier.
     */
    static void (*const suche_wachhund)(void) __attribute__((unused)) = treffer_aufgegeben;
    for (;;) {
        if (k >= 256) {
            goto suche_ende;
        }
        if (passt(k, proto, quelle, ziel, qport, zport, flaggen) == 1) {
            antwort = k;
            goto suche_ende;
        }
        if (k < 256) {
            k += 1;
        } else {
            goto suche_ende;
        }
    }
    suche_ende: ;
    return antwort;
}

static uint32_t zaehle_weiter(uint32_t u) {
    zaehle_urteil(u);
    return u;
}

uint32_t entscheide(uint32_t laenge, uint32_t faden) {
    if (faden > 15) {
        zaehle_urteil(DROP);
        return DROP;
    }
    uint32_t ok = entpacke(laenge);
    if (ok == 0) {
        zaehle_fehl();
        zaehle_urteil(DROP);
        return DROP;
    }
    uint32_t proto = gib_kopf_proto();
    uint32_t quelle = gib_kopf_quelle();
    uint32_t ziel = gib_kopf_ziel();
    uint32_t qport = gib_kopf_qport();
    uint32_t zport = gib_kopf_zport();
    uint32_t flaggen = gib_kopf_flaggen();
    uint32_t richtung = 0;
    if (quelle > ziel) {
        richtung = 1;
    } else {
        if (quelle == ziel) {
            if (qport > zport) {
                richtung = 1;
            }
        }
    }
    uint32_t jetzt = tick();
    uint32_t zustand = FREI;
    VSPERRE_nimm();
    {
        zustand = suche_oder_lege_an(quelle, ziel, qport, zport, proto, flaggen, jetzt);
    }
    VSPERRE_gib();
    if (zustand == BESTEHEND && richtung == 0) {
        zaehle_urteil(NIMM_AN);
        return NIMM_AN;
    }
    if (zustand == FREI) {
        zaehle_voll();
    }
    uint32_t urteil = entscheide_regeln(proto, quelle, ziel, qport, zport, flaggen);
    uint32_t treffer = treffer_index(proto, quelle, ziel, qport, zport, flaggen);
    if (treffer <= 255) {
        zaehle_regel(treffer);
    }
    return zaehle_weiter(urteil);
}
