/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>
/* The shift and conversion this generator relies on are implementation-defined in C11 --
 * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.
 * Two's complement itself is the language's own rule and needs no probe. */
_Static_assert((-1 >> 1) == -1, "arithmetic right shift");
_Static_assert((int)0xFFFFFFFFu == -1, "modular conversion");

/* Proved under the following assumptions (SYNTAX.md 12).
 * Each is a statement about the MACHINE that this program takes on
 * trust. A falsifier names the probe that could refute it.
 *   rechner_klein_endian (assume): falsifier sonde_klein_endian
 */

#define EMPFANG_GROESSE 8192u

#define SENDEN_GROESSE 64u

#define KOPF_NETZ 16u

#define KOPF_FAMILIE 4u

#define KOPF_ATTR 4u

#define TYP_PAKET 768u

#define TYP_URTEIL 769u

#define TYP_EINSTELL 770u

#define ATTR_PAKET_KOPF 1u

#define ATTR_URTEIL_KOPF 2u

#define ATTR_NUTZLAST 10u

#define ATTR_EINSTELL_BEFEHL 1u

#define ATTR_EINSTELL_WERTE 2u

#define ATTR_WARTELANG 3u

#define ATTR_MASKE 4u

#define ATTR_MERKMALE 5u

#define BEFEHL_BINDEN 1u

#define KOPIE_PAKET 2u

#define MERKMAL_OFFEN 1u

#define KOPIE_BREITE 1600u

#define WARTESCHLANGE 1024u

#define KENNUNG_ANFRAGE 1u

#define NETZ_AUSGABE 0u

#define BEREIT 0u

#define KURZ 1u

#define TYP_FEHLER 2u

#define ATTR_FEHLER 3u

#define IDS_FEHLER 4u

#define LEER 5u

typedef struct {
    uint32_t byte;
} Empfang_slot;

typedef struct {
    Empfang_slot slots[EMPFANG_GROESSE];
} Empfang;
/* `Empfang` is addressed by NAME: the table IS the storage (beispiele/09). */
static Empfang Empfang_speicher;
#define Empfang_NONE (EMPFANG_GROESSE)

typedef struct {
    uint32_t byte;
} Senden_slot;

typedef struct {
    Senden_slot slots[SENDEN_GROESSE];
} Senden;
/* `Senden` is addressed by NAME: the table IS the storage (beispiele/09). */
static Senden Senden_speicher;
#define Senden_NONE (SENDEN_GROESSE)

typedef struct {
    uint32_t zustand;
    uint32_t kennung;
    uint32_t versatz;
    uint32_t laenge;
    uint32_t reihung;
    uint32_t haken;
    uint32_t typ;
} Ergebnis_slot;

typedef struct {
    Ergebnis_slot slots[1];
} Ergebnis;
/* `Ergebnis` is addressed by NAME: the table IS the storage (beispiele/09). */
static Ergebnis Ergebnis_speicher;
#define Ergebnis_NONE (1)

static bool sonde_klein_endian(void) __attribute__((const)) __attribute__((unused));

_Noreturn void netz_streit(void);

uint32_t drehe32(uint32_t x) __attribute__((const));

uint32_t drehe16(uint32_t x) __attribute__((const));

void lege_empfang(uint32_t i, uint32_t w);

uint32_t hole_senden(uint32_t i) __attribute__((pure));

uint32_t hole_nutzlast(uint32_t i) __attribute__((pure));

uint32_t gib_zustand(void) __attribute__((pure));

uint32_t gib_kennung(void) __attribute__((pure));

uint32_t gib_laenge(void) __attribute__((pure));

uint32_t gib_versatz(void) __attribute__((pure));

uint32_t gib_reihung(void) __attribute__((pure));

uint32_t gib_haken(void) __attribute__((pure));

uint32_t gib_typ(void) __attribute__((pure));

uint32_t baue_binden(uint32_t reihung);

uint32_t baue_werte(uint32_t reihung, uint32_t bereich, uint32_t modus);

uint32_t baue_wartelang(uint32_t reihung, uint32_t maximum);

uint32_t baue_merkmale(uint32_t reihung, uint32_t maske, uint32_t merkmale);

uint32_t baue_urteil(uint32_t kennung, uint32_t urteil, uint32_t reihung);

static uint32_t ergebnis_leer(uint32_t grund, uint32_t typ) __attribute__((unused));

uint32_t suche_paket(uint32_t meldung);

static bool sonde_klein_endian(void) {
    return true;
}

uint32_t drehe32(uint32_t x) {
    uint32_t b0 = x & 255;
    uint32_t b1 = (x >> 8) & 255;
    uint32_t b2 = (x >> 16) & 255;
    uint32_t b3 = (x >> 24) & 255;
    uint32_t t0 = b0 * 16777216;
    uint32_t t1 = b1 * 65536;
    uint32_t t2 = b2 * 256;
    return t0 + t1 + t2 + b3;
}

uint32_t drehe16(uint32_t x) {
    uint32_t lo = x & 255;
    uint32_t hi = (x >> 8) & 255;
    return lo * 256 + hi;
}

void lege_empfang(uint32_t i, uint32_t w) {
    Empfang_speicher.slots[i].byte = w;
    return;
}

uint32_t hole_senden(uint32_t i) {
    return Senden_speicher.slots[i].byte;
}

uint32_t hole_nutzlast(uint32_t i) {
    uint32_t grenze = Ergebnis_speicher.slots[0].laenge;
    if (i >= grenze) {
        return 0;
    }
    uint32_t anfang = Ergebnis_speicher.slots[0].versatz;
    uint32_t s = anfang + i;
    if (!(s <= 8191)) {
        return 0;
    }
    return Empfang_speicher.slots[s].byte;
}

uint32_t gib_zustand(void) {
    return Ergebnis_speicher.slots[0].zustand;
}

uint32_t gib_kennung(void) {
    return Ergebnis_speicher.slots[0].kennung;
}

uint32_t gib_laenge(void) {
    return Ergebnis_speicher.slots[0].laenge;
}

uint32_t gib_versatz(void) {
    return Ergebnis_speicher.slots[0].versatz;
}

uint32_t gib_reihung(void) {
    return Ergebnis_speicher.slots[0].reihung;
}

uint32_t gib_haken(void) {
    return Ergebnis_speicher.slots[0].haken;
}

uint32_t gib_typ(void) {
    return Ergebnis_speicher.slots[0].typ;
}

uint32_t baue_binden(uint32_t reihung) {
    uint32_t qid = drehe16(reihung);
    Senden_speicher.slots[0].byte = 28;
    Senden_speicher.slots[1].byte = 0;
    Senden_speicher.slots[2].byte = 0;
    Senden_speicher.slots[3].byte = 0;
    Senden_speicher.slots[4].byte = 2;
    Senden_speicher.slots[5].byte = 3;
    Senden_speicher.slots[6].byte = 1;
    Senden_speicher.slots[7].byte = 0;
    Senden_speicher.slots[8].byte = 0;
    Senden_speicher.slots[9].byte = 0;
    Senden_speicher.slots[10].byte = 0;
    Senden_speicher.slots[11].byte = 0;
    Senden_speicher.slots[12].byte = 0;
    Senden_speicher.slots[13].byte = 0;
    Senden_speicher.slots[14].byte = 0;
    Senden_speicher.slots[15].byte = 0;
    Senden_speicher.slots[16].byte = 0;
    Senden_speicher.slots[17].byte = 0;
    Senden_speicher.slots[18].byte = qid & 255;
    Senden_speicher.slots[19].byte = (qid >> 8) & 255;
    Senden_speicher.slots[20].byte = 8;
    Senden_speicher.slots[21].byte = 0;
    Senden_speicher.slots[22].byte = 1;
    Senden_speicher.slots[23].byte = 0;
    Senden_speicher.slots[24].byte = 1;
    Senden_speicher.slots[25].byte = 0;
    Senden_speicher.slots[26].byte = 0;
    Senden_speicher.slots[27].byte = 0;
    return 28;
}

uint32_t baue_werte(uint32_t reihung, uint32_t bereich, uint32_t modus) {
    uint32_t qid = drehe16(reihung);
    uint32_t weit = drehe32(bereich);
    Senden_speicher.slots[0].byte = 32;
    Senden_speicher.slots[1].byte = 0;
    Senden_speicher.slots[2].byte = 0;
    Senden_speicher.slots[3].byte = 0;
    Senden_speicher.slots[4].byte = 2;
    Senden_speicher.slots[5].byte = 3;
    Senden_speicher.slots[6].byte = 1;
    Senden_speicher.slots[7].byte = 0;
    Senden_speicher.slots[8].byte = 0;
    Senden_speicher.slots[9].byte = 0;
    Senden_speicher.slots[10].byte = 0;
    Senden_speicher.slots[11].byte = 0;
    Senden_speicher.slots[12].byte = 0;
    Senden_speicher.slots[13].byte = 0;
    Senden_speicher.slots[14].byte = 0;
    Senden_speicher.slots[15].byte = 0;
    Senden_speicher.slots[16].byte = 0;
    Senden_speicher.slots[17].byte = 0;
    Senden_speicher.slots[18].byte = qid & 255;
    Senden_speicher.slots[19].byte = (qid >> 8) & 255;
    Senden_speicher.slots[20].byte = 9;
    Senden_speicher.slots[21].byte = 0;
    Senden_speicher.slots[22].byte = 2;
    Senden_speicher.slots[23].byte = 0;
    Senden_speicher.slots[24].byte = weit & 255;
    Senden_speicher.slots[25].byte = (weit >> 8) & 255;
    Senden_speicher.slots[26].byte = (weit >> 16) & 255;
    Senden_speicher.slots[27].byte = (weit >> 24) & 255;
    Senden_speicher.slots[28].byte = modus;
    Senden_speicher.slots[29].byte = 0;
    Senden_speicher.slots[30].byte = 0;
    Senden_speicher.slots[31].byte = 0;
    return 32;
}

uint32_t baue_wartelang(uint32_t reihung, uint32_t maximum) {
    uint32_t qid = drehe16(reihung);
    uint32_t tief = drehe32(maximum);
    Senden_speicher.slots[0].byte = 28;
    Senden_speicher.slots[1].byte = 0;
    Senden_speicher.slots[2].byte = 0;
    Senden_speicher.slots[3].byte = 0;
    Senden_speicher.slots[4].byte = 2;
    Senden_speicher.slots[5].byte = 3;
    Senden_speicher.slots[6].byte = 1;
    Senden_speicher.slots[7].byte = 0;
    Senden_speicher.slots[8].byte = 0;
    Senden_speicher.slots[9].byte = 0;
    Senden_speicher.slots[10].byte = 0;
    Senden_speicher.slots[11].byte = 0;
    Senden_speicher.slots[12].byte = 0;
    Senden_speicher.slots[13].byte = 0;
    Senden_speicher.slots[14].byte = 0;
    Senden_speicher.slots[15].byte = 0;
    Senden_speicher.slots[16].byte = 0;
    Senden_speicher.slots[17].byte = 0;
    Senden_speicher.slots[18].byte = qid & 255;
    Senden_speicher.slots[19].byte = (qid >> 8) & 255;
    Senden_speicher.slots[20].byte = 8;
    Senden_speicher.slots[21].byte = 0;
    Senden_speicher.slots[22].byte = 3;
    Senden_speicher.slots[23].byte = 0;
    Senden_speicher.slots[24].byte = tief & 255;
    Senden_speicher.slots[25].byte = (tief >> 8) & 255;
    Senden_speicher.slots[26].byte = (tief >> 16) & 255;
    Senden_speicher.slots[27].byte = (tief >> 24) & 255;
    return 28;
}

uint32_t baue_merkmale(uint32_t reihung, uint32_t maske, uint32_t merkmale) {
    uint32_t qid = drehe16(reihung);
    uint32_t decke = drehe32(maske);
    uint32_t zeichen = drehe32(merkmale);
    Senden_speicher.slots[0].byte = 36;
    Senden_speicher.slots[1].byte = 0;
    Senden_speicher.slots[2].byte = 0;
    Senden_speicher.slots[3].byte = 0;
    Senden_speicher.slots[4].byte = 2;
    Senden_speicher.slots[5].byte = 3;
    Senden_speicher.slots[6].byte = 1;
    Senden_speicher.slots[7].byte = 0;
    Senden_speicher.slots[8].byte = 0;
    Senden_speicher.slots[9].byte = 0;
    Senden_speicher.slots[10].byte = 0;
    Senden_speicher.slots[11].byte = 0;
    Senden_speicher.slots[12].byte = 0;
    Senden_speicher.slots[13].byte = 0;
    Senden_speicher.slots[14].byte = 0;
    Senden_speicher.slots[15].byte = 0;
    Senden_speicher.slots[16].byte = 0;
    Senden_speicher.slots[17].byte = 0;
    Senden_speicher.slots[18].byte = qid & 255;
    Senden_speicher.slots[19].byte = (qid >> 8) & 255;
    Senden_speicher.slots[20].byte = 8;
    Senden_speicher.slots[21].byte = 0;
    Senden_speicher.slots[22].byte = 4;
    Senden_speicher.slots[23].byte = 0;
    Senden_speicher.slots[24].byte = decke & 255;
    Senden_speicher.slots[25].byte = (decke >> 8) & 255;
    Senden_speicher.slots[26].byte = (decke >> 16) & 255;
    Senden_speicher.slots[27].byte = (decke >> 24) & 255;
    Senden_speicher.slots[28].byte = 8;
    Senden_speicher.slots[29].byte = 0;
    Senden_speicher.slots[30].byte = 5;
    Senden_speicher.slots[31].byte = 0;
    Senden_speicher.slots[32].byte = zeichen & 255;
    Senden_speicher.slots[33].byte = (zeichen >> 8) & 255;
    Senden_speicher.slots[34].byte = (zeichen >> 16) & 255;
    Senden_speicher.slots[35].byte = (zeichen >> 24) & 255;
    return 36;
}

uint32_t baue_urteil(uint32_t kennung, uint32_t urteil, uint32_t reihung) {
    uint32_t qid = drehe16(reihung);
    uint32_t spruch = drehe32(urteil);
    uint32_t paket = drehe32(kennung);
    Senden_speicher.slots[0].byte = 32;
    Senden_speicher.slots[1].byte = 0;
    Senden_speicher.slots[2].byte = 0;
    Senden_speicher.slots[3].byte = 0;
    Senden_speicher.slots[4].byte = 1;
    Senden_speicher.slots[5].byte = 3;
    Senden_speicher.slots[6].byte = 1;
    Senden_speicher.slots[7].byte = 0;
    Senden_speicher.slots[8].byte = 0;
    Senden_speicher.slots[9].byte = 0;
    Senden_speicher.slots[10].byte = 0;
    Senden_speicher.slots[11].byte = 0;
    Senden_speicher.slots[12].byte = 0;
    Senden_speicher.slots[13].byte = 0;
    Senden_speicher.slots[14].byte = 0;
    Senden_speicher.slots[15].byte = 0;
    Senden_speicher.slots[16].byte = 0;
    Senden_speicher.slots[17].byte = 0;
    Senden_speicher.slots[18].byte = qid & 255;
    Senden_speicher.slots[19].byte = (qid >> 8) & 255;
    Senden_speicher.slots[20].byte = 12;
    Senden_speicher.slots[21].byte = 0;
    Senden_speicher.slots[22].byte = 2;
    Senden_speicher.slots[23].byte = 0;
    Senden_speicher.slots[24].byte = spruch & 255;
    Senden_speicher.slots[25].byte = (spruch >> 8) & 255;
    Senden_speicher.slots[26].byte = (spruch >> 16) & 255;
    Senden_speicher.slots[27].byte = (spruch >> 24) & 255;
    Senden_speicher.slots[28].byte = paket & 255;
    Senden_speicher.slots[29].byte = (paket >> 8) & 255;
    Senden_speicher.slots[30].byte = (paket >> 16) & 255;
    Senden_speicher.slots[31].byte = (paket >> 24) & 255;
    return 32;
}

static uint32_t ergebnis_leer(uint32_t grund, uint32_t typ) {
    Ergebnis_speicher.slots[0].zustand = grund;
    Ergebnis_speicher.slots[0].kennung = 0;
    Ergebnis_speicher.slots[0].versatz = 0;
    Ergebnis_speicher.slots[0].laenge = 0;
    Ergebnis_speicher.slots[0].reihung = 0;
    Ergebnis_speicher.slots[0].haken = 0;
    Ergebnis_speicher.slots[0].typ = typ;
    return grund;
}

uint32_t suche_paket(uint32_t meldung) {
    if (meldung < 20) {
        return ergebnis_leer(1, 0);
    }
    uint32_t l0 = Empfang_speicher.slots[0].byte;
    uint32_t l1 = Empfang_speicher.slots[1].byte;
    uint32_t l2 = Empfang_speicher.slots[2].byte;
    uint32_t l3 = Empfang_speicher.slots[3].byte;
    uint32_t mlen = l0 + l1 * 256 + l2 * 65536 + l3 * 16777216;
    if (mlen < 20) {
        return ergebnis_leer(1, 0);
    }
    if (mlen > meldung) {
        return ergebnis_leer(1, 0);
    }
    uint32_t y0 = Empfang_speicher.slots[4].byte;
    uint32_t y1 = Empfang_speicher.slots[5].byte;
    uint32_t typ = y0 + y1 * 256;
    if (typ != 768) {
        return ergebnis_leer(2, typ);
    }
    uint32_t familie = Empfang_speicher.slots[16].byte;
    if (familie != 0) {
        return ergebnis_leer(2, typ);
    }
    uint32_t ausgabe = Empfang_speicher.slots[17].byte;
    if (ausgabe != 0) {
        return ergebnis_leer(2, typ);
    }
    uint32_t r0 = Empfang_speicher.slots[18].byte;
    uint32_t r1 = Empfang_speicher.slots[19].byte;
    uint32_t reihung = drehe16(r0 + r1 * 256);
    uint32_t versatz = 20;
    uint32_t kennung = 0;
    uint32_t haken = 0;
    uint32_t nutzversatz = 0;
    uint32_t nutzlang = 0;
    uint32_t kopf_da = 0;
    uint32_t last_da = 0;
    uint32_t fehler = 0;
    {
        uint32_t _r1 = 0;
        for (; !(versatz >= mlen) && _r1 < 2083u; _r1 += 1) {
            uint32_t q0 = Empfang_speicher.slots[0].byte;
            uint32_t q1 = Empfang_speicher.slots[1].byte;
            uint32_t q2 = Empfang_speicher.slots[2].byte;
            uint32_t q3 = Empfang_speicher.slots[3].byte;
            uint32_t mlen_now = q0 + q1 * 256 + q2 * 65536 + q3 * 16777216;
            uint32_t a = versatz;
            if (!(a <= 8188)) {
                fehler = 3;
                goto attr_ende;
            }
            uint32_t g0 = Empfang_speicher.slots[a].byte;
            uint32_t g1 = Empfang_speicher.slots[a + 1].byte;
            uint32_t g2 = Empfang_speicher.slots[a + 2].byte;
            uint32_t g3 = Empfang_speicher.slots[a + 3].byte;
            uint32_t alen = g0 + g1 * 256;
            uint32_t atyp = g2 + g3 * 256;
            if (alen < 4) {
                fehler = 3;
                goto attr_ende;
            }
            uint32_t ende = a + alen;
            if (ende > mlen_now) {
                fehler = 3;
                goto attr_ende;
            }
            if (atyp == 1) {
                if (alen < 12) {
                    fehler = 4;
                    goto attr_ende;
                }
                if (!(a <= 8180)) {
                    fehler = 3;
                    goto attr_ende;
                }
                uint32_t k0 = Empfang_speicher.slots[a + 4].byte;
                uint32_t k1 = Empfang_speicher.slots[a + 5].byte;
                uint32_t k2 = Empfang_speicher.slots[a + 6].byte;
                uint32_t k3 = Empfang_speicher.slots[a + 7].byte;
                uint32_t roh = k0 + k1 * 256 + k2 * 65536 + k3 * 16777216;
                kennung = drehe32(roh);
                haken = Empfang_speicher.slots[a + 10].byte;
                kopf_da = 1;
            } else {
                if (atyp == 10) {
                    uint32_t nlen = alen - 4;
                    if (nlen < 1) {
                        fehler = 5;
                        goto attr_ende;
                    }
                    uint32_t pv = a + 4;
                    if (!(pv <= 8191)) {
                        fehler = 3;
                        goto attr_ende;
                    }
                    if (nlen > 1600) {
                        nutzlang = 1600;
                    } else {
                        nutzlang = nlen;
                    }
                    nutzversatz = pv;
                    last_da = 1;
                }
            }
            uint32_t neu = (ende + 3) / 4 * 4;
            if (!(neu <= 8192)) {
                fehler = 3;
                goto attr_ende;
            }
            versatz = neu;
        }
        if (_r1 >= 2083u && !(versatz >= mlen)) { netz_streit(); }
    }
    attr_ende: ;
    uint32_t t0 = Empfang_speicher.slots[4].byte;
    uint32_t t1 = Empfang_speicher.slots[5].byte;
    uint32_t typ_now = t0 + t1 * 256;
    if (fehler != 0) {
        return ergebnis_leer(fehler, typ_now);
    }
    if (kopf_da == 0) {
        return ergebnis_leer(4, typ_now);
    }
    if (last_da == 0) {
        return ergebnis_leer(5, typ_now);
    }
    Ergebnis_speicher.slots[0].zustand = 0;
    Ergebnis_speicher.slots[0].kennung = kennung;
    Ergebnis_speicher.slots[0].versatz = nutzversatz;
    Ergebnis_speicher.slots[0].laenge = nutzlang;
    Ergebnis_speicher.slots[0].reihung = reihung;
    Ergebnis_speicher.slots[0].haken = haken;
    Ergebnis_speicher.slots[0].typ = typ;
    return 0;
}
