/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>
/* The shift and conversion this generator relies on are implementation-defined in C11 --
 * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.
 * Two's complement itself is the language's own rule and needs no probe. */
_Static_assert((-1 >> 1) == -1, "arithmetic right shift");
_Static_assert((int)0xFFFFFFFFu == -1, "modular conversion");

typedef struct {
    uint32_t byte;
} Paket_slot;

typedef struct {
    Paket_slot slots[1600];
} Paket;
/* `Paket` is addressed by NAME: the table IS the storage (beispiele/09). */
static Paket Paket_speicher;
#define Paket_NONE (1600)

typedef struct {
    uint32_t gueltig;
    uint32_t proto;
    uint32_t quelle;
    uint32_t ziel;
    uint32_t qport;
    uint32_t zport;
    uint32_t flaggen;
    uint32_t laenge;
} Kopf_slot;

typedef struct {
    Kopf_slot slots[1];
} Kopf;
/* `Kopf` is addressed by NAME: the table IS the storage (beispiele/09). */
static Kopf Kopf_speicher;
#define Kopf_NONE (1)

static uint32_t ungueltig(void) __attribute__((unused));

uint32_t entpacke(uint32_t laenge);

uint32_t gib_kopf_gueltig(void) __attribute__((pure));

uint32_t gib_kopf_proto(void) __attribute__((pure));

uint32_t gib_kopf_quelle(void) __attribute__((pure));

uint32_t gib_kopf_ziel(void) __attribute__((pure));

uint32_t gib_kopf_qport(void) __attribute__((pure));

uint32_t gib_kopf_zport(void) __attribute__((pure));

uint32_t gib_kopf_flaggen(void) __attribute__((pure));

uint32_t gib_kopf_laenge(void) __attribute__((pure));

static uint32_t ungueltig(void) {
    Kopf_speicher.slots[0].gueltig = 0;
    Kopf_speicher.slots[0].proto = 0;
    Kopf_speicher.slots[0].quelle = 0;
    Kopf_speicher.slots[0].ziel = 0;
    Kopf_speicher.slots[0].qport = 0;
    Kopf_speicher.slots[0].zport = 0;
    Kopf_speicher.slots[0].flaggen = 0;
    Kopf_speicher.slots[0].laenge = 0;
    return 0;
}

uint32_t entpacke(uint32_t laenge) {
    if (laenge < 14) {
        return ungueltig();
    }
    uint32_t et0 = Paket_speicher.slots[12].byte;
    uint32_t et1 = Paket_speicher.slots[13].byte;
    uint32_t etyp = et0 * 256 + et1;
    if (etyp != 2048) {
        return ungueltig();
    }
    if (laenge < 34) {
        return ungueltig();
    }
    uint32_t vio = Paket_speicher.slots[14].byte;
    uint32_t version = vio >> 4;
    if (version != 4) {
        return ungueltig();
    }
    uint32_t ihl = vio & 15;
    if (ihl < 5) {
        return ungueltig();
    }
    uint32_t hlen = ihl * 4;
    uint32_t bo = 14 + hlen;
    if (laenge < bo) {
        return ungueltig();
    }
    uint32_t t0 = Paket_speicher.slots[16].byte;
    uint32_t t1 = Paket_speicher.slots[17].byte;
    uint32_t tot = t0 * 256 + t1;
    uint32_t f0 = Paket_speicher.slots[20].byte;
    uint32_t f1 = Paket_speicher.slots[21].byte;
    uint32_t mf = f0 & 32;
    uint32_t oh = f0 & 31;
    uint32_t versatz = oh * 256 + f1;
    uint32_t proto = Paket_speicher.slots[23].byte;
    uint32_t q0 = Paket_speicher.slots[26].byte;
    uint32_t q1 = Paket_speicher.slots[27].byte;
    uint32_t q2 = Paket_speicher.slots[28].byte;
    uint32_t q3 = Paket_speicher.slots[29].byte;
    uint32_t qa0 = q0 * 16777216;
    uint32_t qa1 = q1 * 65536;
    uint32_t qa2 = q2 * 256;
    uint32_t quelle = qa0 + qa1 + qa2 + q3;
    uint32_t z0 = Paket_speicher.slots[30].byte;
    uint32_t z1 = Paket_speicher.slots[31].byte;
    uint32_t z2 = Paket_speicher.slots[32].byte;
    uint32_t z3 = Paket_speicher.slots[33].byte;
    uint32_t za0 = z0 * 16777216;
    uint32_t za1 = z1 * 65536;
    uint32_t za2 = z2 * 256;
    uint32_t ziel = za0 + za1 + za2 + z3;
    uint32_t qport = 0;
    uint32_t zport = 0;
    uint32_t flaggen = 0;
    if (!(bo <= 1599)) {
        return ungueltig();
    }
    if (proto == 6) {
        if (mf != 0) {
            return ungueltig();
        }
        if (versatz != 0) {
            return ungueltig();
        }
        if (laenge < bo + 14) {
            return ungueltig();
        }
        uint32_t s0 = Paket_speicher.slots[bo].byte;
        uint32_t s1 = Paket_speicher.slots[bo + 1].byte;
        uint32_t d0 = Paket_speicher.slots[bo + 2].byte;
        uint32_t d1 = Paket_speicher.slots[bo + 3].byte;
        uint32_t fl = Paket_speicher.slots[bo + 13].byte;
        qport = s0 * 256 + s1;
        zport = d0 * 256 + d1;
        flaggen = fl;
    } else {
        if (proto == 17) {
            if (mf != 0) {
                return ungueltig();
            }
            if (versatz != 0) {
                return ungueltig();
            }
            if (laenge < bo + 4) {
                return ungueltig();
            }
            uint32_t u0 = Paket_speicher.slots[bo].byte;
            uint32_t u1 = Paket_speicher.slots[bo + 1].byte;
            uint32_t v0 = Paket_speicher.slots[bo + 2].byte;
            uint32_t v1 = Paket_speicher.slots[bo + 3].byte;
            qport = u0 * 256 + u1;
            zport = v0 * 256 + v1;
        } else {
            if (proto == 1) {
            } else {
                return ungueltig();
            }
        }
    }
    Kopf_speicher.slots[0].gueltig = 1;
    Kopf_speicher.slots[0].proto = proto;
    Kopf_speicher.slots[0].quelle = quelle;
    Kopf_speicher.slots[0].ziel = ziel;
    Kopf_speicher.slots[0].qport = qport;
    Kopf_speicher.slots[0].zport = zport;
    Kopf_speicher.slots[0].flaggen = flaggen;
    Kopf_speicher.slots[0].laenge = tot;
    return 1;
}

uint32_t gib_kopf_gueltig(void) {
    return Kopf_speicher.slots[0].gueltig;
}

uint32_t gib_kopf_proto(void) {
    return Kopf_speicher.slots[0].proto;
}

uint32_t gib_kopf_quelle(void) {
    return Kopf_speicher.slots[0].quelle;
}

uint32_t gib_kopf_ziel(void) {
    return Kopf_speicher.slots[0].ziel;
}

uint32_t gib_kopf_qport(void) {
    return Kopf_speicher.slots[0].qport;
}

uint32_t gib_kopf_zport(void) {
    return Kopf_speicher.slots[0].zport;
}

uint32_t gib_kopf_flaggen(void) {
    return Kopf_speicher.slots[0].flaggen;
}

uint32_t gib_kopf_laenge(void) {
    return Kopf_speicher.slots[0].laenge;
}
