/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>
/* The shift and conversion this generator relies on are implementation-defined in C11 --
 * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.
 * Two's complement itself is the language's own rule and needs no probe. */
_Static_assert((-1 >> 1) == -1, "arithmetic right shift");
_Static_assert((int)0xFFFFFFFFu == -1, "modular conversion");

#define REGELZAHL 256u

#define VERWIRF 0u

#define NIMM_AN 1u

#define WEISE_AB 2u

#define STANDARD 0u

typedef struct {
    uint32_t aktiv;
    uint32_t proto_any;
    uint32_t proto;
    uint32_t quell_any;
    uint32_t quelle;
    uint32_t qmask;
    uint32_t ziel_any;
    uint32_t ziel;
    uint32_t zmask;
    uint32_t qport_any;
    uint32_t qport_lo;
    uint32_t qport_hi;
    uint32_t zport_any;
    uint32_t zport_lo;
    uint32_t zport_hi;
    uint32_t flaggen_any;
    uint32_t flaggen_maske;
    uint32_t flaggen_wert;
    uint32_t urteil;
    uint32_t nummer;
} Regel_slot;

typedef struct {
    Regel_slot slots[REGELZAHL];
} Regel;
/* `Regel` is addressed by NAME: the table IS the storage (beispiele/09). */
static Regel Regel_speicher;
#define Regel_NONE (REGELZAHL)

uint32_t passt(uint32_t r, uint32_t proto, uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t flaggen) __attribute__((pure));

uint32_t entscheide_regeln(uint32_t proto, uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t flaggen);

void setze_regel(uint32_t i, uint32_t aktiv, uint32_t proto_any, uint32_t proto, uint32_t quell_any, uint32_t quelle, uint32_t qmask, uint32_t ziel_any, uint32_t ziel, uint32_t zmask, uint32_t qport_any, uint32_t qport_lo, uint32_t qport_hi, uint32_t zport_any, uint32_t zport_lo, uint32_t zport_hi, uint32_t flaggen_any, uint32_t flaggen_maske, uint32_t flaggen_wert, uint32_t urteil, uint32_t nummer);

void raeume_alle(void);

uint32_t passt(uint32_t r, uint32_t proto, uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t flaggen) {
    if (Regel_speicher.slots[r].aktiv == 0) {
        return 0;
    }
    if (Regel_speicher.slots[r].proto_any == 0) {
        if (Regel_speicher.slots[r].proto != proto) {
            return 0;
        }
    }
    if (Regel_speicher.slots[r].quell_any == 0) {
        if ((quelle & Regel_speicher.slots[r].qmask) != (Regel_speicher.slots[r].quelle & Regel_speicher.slots[r].qmask)) {
            return 0;
        }
    }
    if (Regel_speicher.slots[r].ziel_any == 0) {
        if ((ziel & Regel_speicher.slots[r].zmask) != (Regel_speicher.slots[r].ziel & Regel_speicher.slots[r].zmask)) {
            return 0;
        }
    }
    if (Regel_speicher.slots[r].qport_any == 0) {
        if (qport < Regel_speicher.slots[r].qport_lo) {
            return 0;
        }
        if (qport > Regel_speicher.slots[r].qport_hi) {
            return 0;
        }
    }
    if (Regel_speicher.slots[r].zport_any == 0) {
        if (zport < Regel_speicher.slots[r].zport_lo) {
            return 0;
        }
        if (zport > Regel_speicher.slots[r].zport_hi) {
            return 0;
        }
    }
    if (Regel_speicher.slots[r].flaggen_any == 0) {
        if ((flaggen & Regel_speicher.slots[r].flaggen_maske) != (Regel_speicher.slots[r].flaggen_wert & Regel_speicher.slots[r].flaggen_maske)) {
            return 0;
        }
    }
    return 1;
}

uint32_t entscheide_regeln(uint32_t proto, uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t flaggen) {
    for (uint32_t k = 0; k < (uint32_t)(sizeof(Regel_speicher.slots) / sizeof(Regel_speicher.slots[0])); k += 1) {
        if (passt(k, proto, quelle, ziel, qport, zport, flaggen) == 1) {
            return Regel_speicher.slots[k].urteil;
        }
    }
    return STANDARD;
}

void setze_regel(uint32_t i, uint32_t aktiv, uint32_t proto_any, uint32_t proto, uint32_t quell_any, uint32_t quelle, uint32_t qmask, uint32_t ziel_any, uint32_t ziel, uint32_t zmask, uint32_t qport_any, uint32_t qport_lo, uint32_t qport_hi, uint32_t zport_any, uint32_t zport_lo, uint32_t zport_hi, uint32_t flaggen_any, uint32_t flaggen_maske, uint32_t flaggen_wert, uint32_t urteil, uint32_t nummer) {
    Regel_speicher.slots[i].aktiv = aktiv;
    Regel_speicher.slots[i].proto_any = proto_any;
    Regel_speicher.slots[i].proto = proto;
    Regel_speicher.slots[i].quell_any = quell_any;
    Regel_speicher.slots[i].quelle = quelle;
    Regel_speicher.slots[i].qmask = qmask;
    Regel_speicher.slots[i].ziel_any = ziel_any;
    Regel_speicher.slots[i].ziel = ziel;
    Regel_speicher.slots[i].zmask = zmask;
    Regel_speicher.slots[i].qport_any = qport_any;
    Regel_speicher.slots[i].qport_lo = qport_lo;
    Regel_speicher.slots[i].qport_hi = qport_hi;
    Regel_speicher.slots[i].zport_any = zport_any;
    Regel_speicher.slots[i].zport_lo = zport_lo;
    Regel_speicher.slots[i].zport_hi = zport_hi;
    Regel_speicher.slots[i].flaggen_any = flaggen_any;
    Regel_speicher.slots[i].flaggen_maske = flaggen_maske;
    Regel_speicher.slots[i].flaggen_wert = flaggen_wert;
    Regel_speicher.slots[i].urteil = urteil;
    Regel_speicher.slots[i].nummer = nummer;
    return;
}

void raeume_alle(void) {
    for (uint32_t k = 0; k < (uint32_t)(sizeof(Regel_speicher.slots) / sizeof(Regel_speicher.slots[0])); k += 1) {
        Regel_speicher.slots[k].aktiv = 0;
        Regel_speicher.slots[k].urteil = STANDARD;
    }
    return;
}
