/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>
/* The shift and conversion this generator relies on are implementation-defined in C11 --
 * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.
 * Two's complement itself is the language's own rule and needs no probe. */
_Static_assert((-1 >> 1) == -1, "arithmetic right shift");
_Static_assert((int)0xFFFFFFFFu == -1, "modular conversion");

#define ANZAHL 4096u

#define EIMER 1024u

#define FACH 4u

#define ABLAUF 300u

typedef struct {
    uint32_t zustand;
    uint32_t adr_a;
    uint32_t adr_b;
    uint32_t port_a;
    uint32_t port_b;
    uint32_t iprot;
    uint32_t gesehen;
    uint32_t hin;
    uint32_t rueck;
} Verbindung_slot;

typedef struct {
    Verbindung_slot slots[ANZAHL];
} Verbindung;
/* `Verbindung` is addressed by NAME: the table IS the storage (beispiele/09). */
static Verbindung Verbindung_speicher;
#define Verbindung_NONE (ANZAHL)

typedef struct {
    uint32_t voll;
    uint32_t neu;
    uint32_t treffer;
    uint32_t abgelaufen;
} Stand_slot;

typedef struct {
    Stand_slot slots[1];
} Stand;
/* `Stand` is addressed by NAME: the table IS the storage (beispiele/09). */
static Stand Stand_speicher;
#define Stand_NONE (1)

void VSPERRE_nimm(void);
void VSPERRE_gib(void);

static uint32_t treffer_pflegen(uint32_t s, uint32_t richtung, uint32_t flaggen, uint32_t jetzt) __attribute__((unused));

uint32_t suche_oder_lege_an(uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t iprot, uint32_t flaggen, uint32_t jetzt);

void altere(uint32_t jetzt);

uint32_t lies_stand(uint32_t w);

static uint32_t treffer_pflegen(uint32_t s, uint32_t richtung, uint32_t flaggen, uint32_t jetzt) {
    Verbindung_speicher.slots[s].gesehen = jetzt;
    if (richtung == 0) {
        if (Verbindung_speicher.slots[s].hin < 4294967295u) {
            Verbindung_speicher.slots[s].hin += 1;
        }
    } else {
        if (Verbindung_speicher.slots[s].rueck < 4294967295u) {
            Verbindung_speicher.slots[s].rueck += 1;
        }
    }
    uint32_t z = Verbindung_speicher.slots[s].zustand;
    uint32_t neu_zustand = z;
    if (z == 1) {
        if (richtung == 1) {
            neu_zustand = 2;
        }
    } else {
        if (z == 2) {
            uint32_t f = flaggen & 5;
            if (f != 0) {
                neu_zustand = 3;
            }
        }
    }
    Verbindung_speicher.slots[s].zustand = neu_zustand;
    uint32_t frisch = Verbindung_speicher.slots[s].zustand;
    if (Stand_speicher.slots[0].treffer < 4294967295u) {
        Stand_speicher.slots[0].treffer += 1;
    }
    return frisch;
}

uint32_t suche_oder_lege_an(uint32_t quelle, uint32_t ziel, uint32_t qport, uint32_t zport, uint32_t iprot, uint32_t flaggen, uint32_t jetzt) {
    uint32_t a = quelle;
    uint32_t b = ziel;
    uint32_t pa = qport;
    uint32_t pb = zport;
    uint32_t richtung = 0;
    if (quelle > ziel) {
        a = ziel;
        b = quelle;
        pa = zport;
        pb = qport;
        richtung = 1;
    } else {
        if (quelle == ziel) {
            if (qport > zport) {
                a = ziel;
                b = quelle;
                pa = zport;
                pb = qport;
                richtung = 1;
            }
        }
    }
    uint32_t h = (((a ^ b) ^ pa) ^ pb) ^ iprot;
    uint32_t eimer = h % EIMER;
    uint32_t frei = ANZAHL;
    uint32_t s0 = eimer * 4 + 0;
    if (!(s0 < ANZAHL)) {
        return 0;
    }
    if (Verbindung_speicher.slots[s0].zustand != 0) {
        if (Verbindung_speicher.slots[s0].adr_a == a && Verbindung_speicher.slots[s0].adr_b == b && Verbindung_speicher.slots[s0].port_a == pa && Verbindung_speicher.slots[s0].port_b == pb && Verbindung_speicher.slots[s0].iprot == iprot) {
            return treffer_pflegen(s0, richtung, flaggen, jetzt);
        }
    } else {
        if (frei == ANZAHL) {
            frei = s0;
        }
    }
    uint32_t s1 = eimer * 4 + 1;
    if (!(s1 < ANZAHL)) {
        return 0;
    }
    if (Verbindung_speicher.slots[s1].zustand != 0) {
        if (Verbindung_speicher.slots[s1].adr_a == a && Verbindung_speicher.slots[s1].adr_b == b && Verbindung_speicher.slots[s1].port_a == pa && Verbindung_speicher.slots[s1].port_b == pb && Verbindung_speicher.slots[s1].iprot == iprot) {
            return treffer_pflegen(s1, richtung, flaggen, jetzt);
        }
    } else {
        if (frei == ANZAHL) {
            frei = s1;
        }
    }
    uint32_t s2 = eimer * 4 + 2;
    if (!(s2 < ANZAHL)) {
        return 0;
    }
    if (Verbindung_speicher.slots[s2].zustand != 0) {
        if (Verbindung_speicher.slots[s2].adr_a == a && Verbindung_speicher.slots[s2].adr_b == b && Verbindung_speicher.slots[s2].port_a == pa && Verbindung_speicher.slots[s2].port_b == pb && Verbindung_speicher.slots[s2].iprot == iprot) {
            return treffer_pflegen(s2, richtung, flaggen, jetzt);
        }
    } else {
        if (frei == ANZAHL) {
            frei = s2;
        }
    }
    uint32_t s3 = eimer * 4 + 3;
    if (!(s3 < ANZAHL)) {
        return 0;
    }
    if (Verbindung_speicher.slots[s3].zustand != 0) {
        if (Verbindung_speicher.slots[s3].adr_a == a && Verbindung_speicher.slots[s3].adr_b == b && Verbindung_speicher.slots[s3].port_a == pa && Verbindung_speicher.slots[s3].port_b == pb && Verbindung_speicher.slots[s3].iprot == iprot) {
            return treffer_pflegen(s3, richtung, flaggen, jetzt);
        }
    } else {
        if (frei == ANZAHL) {
            frei = s3;
        }
    }
    if (!(frei < ANZAHL)) {
        if (Stand_speicher.slots[0].voll < 4294967295u) {
            Stand_speicher.slots[0].voll += 1;
        }
        return 0;
    }
    Verbindung_speicher.slots[frei].adr_a = a;
    Verbindung_speicher.slots[frei].adr_b = b;
    Verbindung_speicher.slots[frei].port_a = pa;
    Verbindung_speicher.slots[frei].port_b = pb;
    Verbindung_speicher.slots[frei].iprot = iprot;
    Verbindung_speicher.slots[frei].gesehen = jetzt;
    if (richtung == 0) {
        Verbindung_speicher.slots[frei].hin = 1;
        Verbindung_speicher.slots[frei].rueck = 0;
    } else {
        Verbindung_speicher.slots[frei].hin = 0;
        Verbindung_speicher.slots[frei].rueck = 1;
    }
    Verbindung_speicher.slots[frei].zustand = 1;
    if (Stand_speicher.slots[0].neu < 4294967295u) {
        Stand_speicher.slots[0].neu += 1;
    }
    return 1;
}

void altere(uint32_t jetzt) {
    for (uint32_t k = 0; k < (uint32_t)(sizeof(Verbindung_speicher.slots) / sizeof(Verbindung_speicher.slots[0])); k += 1) {
        if (Verbindung_speicher.slots[k].zustand != 0) {
            if (jetzt >= Verbindung_speicher.slots[k].gesehen) {
                uint32_t alter = jetzt - Verbindung_speicher.slots[k].gesehen;
                if (alter > ABLAUF) {
                    Verbindung_speicher.slots[k].zustand = 0;
                    if (Stand_speicher.slots[0].abgelaufen < 4294967295u) {
                        Stand_speicher.slots[0].abgelaufen += 1;
                    }
                }
            }
        }
    }
}

uint32_t lies_stand(uint32_t w) {
    if (w == 0) {
        return Stand_speicher.slots[0].voll;
    }
    if (w == 1) {
        return Stand_speicher.slots[0].neu;
    }
    if (w == 2) {
        return Stand_speicher.slots[0].treffer;
    }
    return Stand_speicher.slots[0].abgelaufen;
}
