/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>
/* The shift and conversion this generator relies on are implementation-defined in C11 --
 * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.
 * Two's complement itself is the language's own rule and needs no probe. */
_Static_assert((-1 >> 1) == -1, "arithmetic right shift");
_Static_assert((int)0xFFFFFFFFu == -1, "modular conversion");

/* Proved under the following assumptions (SYNTAX.md 12).
 * Each is a statement about the MACHINE that this program takes on
 * trust. A falsifier names the probe that could refute it.
 *   paketstrom_fliesst (assume): falsifier sonde_strom
 *   steckdose_kommt (assume): falsifier sonde_dose
 */

#define KEIN_WERT 18446744073709551615u

#define NOCHMAL 18446744073709551614u

#define PAKETE_VERLOREN 18446744073709551613u

#define WARTESCHLANGE 0u

#define PUFFER_GROESSE 65536u

#define GRENZE 1000000u

static bool sonde_strom(void) __attribute__((const)) __attribute__((unused));

static bool sonde_dose(void) __attribute__((const)) __attribute__((unused));

_Noreturn void lauf_aufgegeben(void);

uint64_t netz_socket(void);

uint64_t netz_empfangen(uint64_t fd, uint64_t puffer, uint64_t laenge, uint64_t zeichen, uint64_t quelle, uint64_t quell_laenge);

uint64_t speicher_karte(uint64_t laenge);

uint64_t anhalten(uint64_t status);

void raeume_alle(void);

void setze_regel(uint32_t i, uint32_t aktiv, uint32_t proto_any, uint32_t proto, uint32_t quell_any, uint32_t quelle, uint32_t qmask, uint32_t ziel_any, uint32_t ziel, uint32_t zmask, uint32_t qport_any, uint32_t qport_lo, uint32_t qport_hi, uint32_t zport_any, uint32_t zport_lo, uint32_t zport_hi, uint32_t flaggen_any, uint32_t flaggen_maske, uint32_t flaggen_wert, uint32_t urteil, uint32_t nummer);

typedef struct {
    uint32_t pakete;
    uint32_t verlust;
    uint32_t nochmal;
    uint32_t fehler;
} LaufStand_slot;

typedef struct {
    LaufStand_slot slots[1];
} LaufStand;
/* `LaufStand` is addressed by NAME: the table IS the storage (beispiele/09). */
static LaufStand LaufStand_speicher;
#define LaufStand_NONE (1)

static void lade_grundregeln(void) __attribute__((unused));

static void arbeite(uint64_t steckdose, uint64_t puffer) __attribute__((unused));

int32_t main(void);

static bool sonde_strom(void) {
    return true;
}

static bool sonde_dose(void) {
    return true;
}

static void lade_grundregeln(void) {
    raeume_alle();
    setze_regel(0, 1, 0, 6, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 80, 80, 1, 0, 0, 1, 0);
    return;
}

static void arbeite(uint64_t steckdose, uint64_t puffer) {
    /* forever runde -- `per_pass … ops` is a claim about ONE pass, and the cost
     * pass has already checked it (W6). Nothing counts here at run time, so
     * `on_exceeded` gets no branch -- it gets the line below instead, which makes
     * the C compiler read the clause a second time.
     * `progress paketstrom_fliesst` is an assumption about the WORLD; nothing static
     * establishes it, and `lauf_aufgegeben` is its falsifier.
     */
    static void (*const runde_wachhund)(void) __attribute__((unused)) = lauf_aufgegeben;
    for (;;) {
        uint64_t v = netz_empfangen(steckdose, puffer, PUFFER_GROESSE, 0, 0, 0);
        if (v == NOCHMAL) {
            if (LaufStand_speicher.slots[0].nochmal < 4294967295u) {
                LaufStand_speicher.slots[0].nochmal += 1;
            }
        } else {
            if (v == PAKETE_VERLOREN) {
                if (LaufStand_speicher.slots[0].verlust < 4294967295u) {
                    LaufStand_speicher.slots[0].verlust += 1;
                }
            } else {
                if (v == KEIN_WERT) {
                    LaufStand_speicher.slots[0].fehler = 120;
                    goto runde_ende;
                } else {
                    if (LaufStand_speicher.slots[0].pakete < 4294967295u) {
                        LaufStand_speicher.slots[0].pakete += 1;
                    }
                    if (LaufStand_speicher.slots[0].pakete >= GRENZE) {
                        goto runde_ende;
                    }
                }
            }
        }
    }
    runde_ende: ;
    return;
}

int32_t main(void) {
    uint64_t steckdose = KEIN_WERT;
    uint32_t versuche = 0;
    /* forever start -- `per_pass … ops` is a claim about ONE pass, and the cost
     * pass has already checked it (W6). Nothing counts here at run time, so
     * `on_exceeded` gets no branch -- it gets the line below instead, which makes
     * the C compiler read the clause a second time.
     * `progress steckdose_kommt` is an assumption about the WORLD; nothing static
     * establishes it, and `lauf_aufgegeben` is its falsifier.
     */
    static void (*const start_wachhund)(void) __attribute__((unused)) = lauf_aufgegeben;
    for (;;) {
        uint64_t s = netz_socket();
        if (s == NOCHMAL) {
            if (versuche < 64) {
                versuche += 1;
            } else {
                goto start_ende;
            }
        } else {
            steckdose = s;
            goto start_ende;
        }
    }
    start_ende: ;
    if (steckdose == KEIN_WERT) {
        (void)anhalten(110);
        return 110;
    }
    if (steckdose == PAKETE_VERLOREN) {
        (void)anhalten(110);
        return 110;
    }
    uint64_t puffer = speicher_karte(PUFFER_GROESSE);
    if (puffer == KEIN_WERT) {
        (void)anhalten(111);
        return 111;
    }
    if (puffer == NOCHMAL) {
        (void)anhalten(111);
        return 111;
    }
    if (puffer == PAKETE_VERLOREN) {
        (void)anhalten(111);
        return 111;
    }
    lade_grundregeln();
    arbeite(steckdose, puffer);
    if (LaufStand_speicher.slots[0].fehler == 120) {
        (void)anhalten(120);
        return 120;
    }
    if (LaufStand_speicher.slots[0].verlust > 0) {
        (void)anhalten(1);
        return 1;
    }
    (void)anhalten(0);
    return 0;
}
