/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>
/* The shift and conversion this generator relies on are implementation-defined in C11 --
 * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.
 * Two's complement itself is the language's own rule and needs no probe. */
_Static_assert((-1 >> 1) == -1, "arithmetic right shift");
_Static_assert((int)0xFFFFFFFFu == -1, "modular conversion");

/* Proved under the following assumptions (SYNTAX.md 12).
 * Each is a statement about the MACHINE that this program takes on
 * trust. A falsifier names the probe that could refute it.
 *   linux_anhalten_vertrag (assume): falsifier sonde_anhalten
 *   linux_bericht_schreiben_vertrag (assume): falsifier sonde_bericht_schreiben
 *   linux_faden_start_vertrag (assume): falsifier sonde_faden_start
 *   linux_netz_binden_vertrag (assume): falsifier sonde_netz_binden
 *   linux_netz_empfangen_vertrag (assume): falsifier sonde_netz_empfangen
 *   linux_netz_senden_vertrag (assume): falsifier sonde_netz_senden
 *   linux_netz_socket_vertrag (assume): falsifier sonde_netz_socket
 *   linux_speicher_karte_vertrag (assume): falsifier sonde_speicher_karte
 *   linux_sperre_vertrag (assume): falsifier sonde_sperre
 *   linux_zeit_lesen_vertrag (assume): falsifier sonde_zeit_lesen
 */

#define AF_NETLINKE 16u

#define SOCK_ROH 3u

#define NETLINKE_FILTER 12u

#define FEHLER_AUSGABE 2u

#define UHR_MONOTON 1u

#define FUTEX_WARTEN 0u

#define FUTEX_WECKEN 1u

#define KARTE_SCHUTZ 3u

#define KARTE_ZEICHEN 34u

#define FADEN_TEILEN 253952u

#define KEIN_WERT 18446744073709551615u

#define NOCHMAL 18446744073709551614u

#define PAKETE_VERLOREN 18446744073709551613u

/* reason NetzFehler */
typedef enum {
    NetzFehler_Unterbrochen = 4, /* EINTR -- unterbrochen; kein Fehler, erneut rufen */
    NetzFehler_Wiederholen = 11, /* EAGAIN -- nichts zu tun oder Wert schon anders; kein Fehler, erneut pruefen */
    NetzFehler_KeinSpeicher = 12, /* ENOMEM -- kein Speicher */
    NetzFehler_PaketeVerloren = 105, /* ENOBUFS -- der Kern hat Pakete verworfen; der Betrieb muss es erfahren */
    NetzFehler_FalscherWert = 22, /* EINVAL -- falscher Wert oder falsche Laenge */
    NetzFehler_SchlechterFd = 9, /* EBADF -- kein offener Dateizeiger */
    NetzFehler_FehlerAdresse = 14, /* EFAULT -- Adresse ausserhalb */
    NetzFehler_FamilieFehlt = 97, /* EAFNOSUPPORT -- Adressfamilie nicht getragen */
    NetzFehler_ProtokollFehlt = 93, /* EPROTONOSUPPORT -- Protokoll nicht getragen */
    NetzFehler_ZuVieleDateien = 24, /* EMFILE -- zu viele offene Dateizeiger in diesem Prozess */
    NetzFehler_SystemVoll = 23, /* ENFILE -- zu viele offene Dateizeiger im System */
    NetzFehler_Verboten = 1, /* EPERM -- nicht erlaubt (Faehigkeit fehlt) */
    NetzFehler_KeinZugriff = 13, /* EACCES -- Zugriff verweigert */
    NetzFehler_ZeitUm = 110, /* ETIMEDOUT -- Frist abgelaufen */
    NetzFehler_LeitungWeg = 32, /* EPIPE -- fernes Ende geschlossen */
} NetzFehler;

static bool sonde_netz_socket(void) __attribute__((const)) __attribute__((unused));

static bool roh_socket(uint64_t gebiet, uint64_t typ, uint64_t protokoll, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_netz_binden(void) __attribute__((const)) __attribute__((unused));

static bool roh_binden(uint64_t fd, uint64_t adresse, uint64_t laenge, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_netz_senden(void) __attribute__((const)) __attribute__((unused));

static bool roh_senden(uint64_t fd, uint64_t nachricht, uint64_t laenge, uint64_t zeichen, uint64_t ziel, uint64_t ziel_laenge, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_netz_empfangen(void) __attribute__((const)) __attribute__((unused));

static bool roh_empfangen(uint64_t fd, uint64_t puffer, uint64_t laenge, uint64_t zeichen, uint64_t quelle, uint64_t quell_laenge, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_speicher_karte(void) __attribute__((const)) __attribute__((unused));

static bool roh_karte(uint64_t adresse, uint64_t laenge, uint64_t schutz, uint64_t zeichen, uint64_t fd, uint64_t versatz, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_faden_start(void) __attribute__((const)) __attribute__((unused));

static bool roh_klonen(uint64_t kind, uint64_t stapel, uint64_t eltern, uint64_t kindspeicher, uint64_t tls, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_sperre(void) __attribute__((const)) __attribute__((unused));

static bool roh_warten(uint64_t adresse, uint64_t vorgang, uint64_t wert, uint64_t frist, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_zeit_lesen(void) __attribute__((const)) __attribute__((unused));

static bool roh_uhr(uint64_t uhr, uint64_t adresse, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_anhalten(void) __attribute__((const)) __attribute__((unused));

static bool roh_ende(uint64_t status, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

static bool sonde_bericht_schreiben(void) __attribute__((const)) __attribute__((unused));

static bool roh_schreiben(uint64_t fd, uint64_t puffer, uint64_t laenge, uint64_t *_wert, NetzFehler *_grund) __attribute__((unused));

uint64_t netz_socket(void);

uint64_t netz_binden(uint64_t fd, uint64_t adresse, uint64_t laenge);

uint64_t netz_senden(uint64_t fd, uint64_t nachricht, uint64_t laenge, uint64_t zeichen, uint64_t ziel, uint64_t ziel_laenge);

uint64_t netz_empfangen(uint64_t fd, uint64_t puffer, uint64_t laenge, uint64_t zeichen, uint64_t quelle, uint64_t quell_laenge);

uint64_t speicher_karte(uint64_t laenge);

uint64_t faden_start(uint64_t kind, uint64_t stapel, uint64_t eltern, uint64_t kindspeicher, uint64_t tls);

uint64_t sperre_warten(uint64_t adresse, uint64_t wert);

uint64_t sperre_wecken(uint64_t adresse, uint64_t anzahl);

uint64_t zeit_lesen(uint64_t uhr, uint64_t adresse);

uint64_t anhalten(uint64_t status);

uint64_t bericht_schreiben(uint64_t adresse, uint64_t laenge);

static bool sonde_netz_socket(void) {
    return true;
}

static bool roh_socket(uint64_t gebiet, uint64_t typ, uint64_t protokoll, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_socket -- number 41 in rax; gebiet in rdi, typ in rsi, protokoll in rdx.
     * The kernel behind this stub is the named assumption `linux_netz_socket_vertrag` (falsifier sonde_netz_socket): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)gebiet;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)typ;
    register uint64_t _sys_rdx __asm__("rdx") = (uint64_t)protokoll;
    register int64_t _sys_rax __asm__("rax") = (int64_t)41u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi), "r" (_sys_rdx)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_netz_socket_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 97) {
            *_grund = NetzFehler_FamilieFehlt;
            return false;
        }
        if (_sys_errno == 93) {
            *_grund = NetzFehler_ProtokollFehlt;
            return false;
        }
        if (_sys_errno == 24) {
            *_grund = NetzFehler_ZuVieleDateien;
            return false;
        }
        if (_sys_errno == 23) {
            *_grund = NetzFehler_SystemVoll;
            return false;
        }
        if (_sys_errno == 12) {
            *_grund = NetzFehler_KeinSpeicher;
            return false;
        }
        if (_sys_errno == 13) {
            *_grund = NetzFehler_KeinZugriff;
            return false;
        }
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 4) {
            *_grund = NetzFehler_Unterbrochen;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_netz_socket_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_netz_binden(void) {
    return true;
}

static bool roh_binden(uint64_t fd, uint64_t adresse, uint64_t laenge, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_binden -- number 49 in rax; fd in rdi, adresse in rsi, laenge in rdx.
     * The kernel behind this stub is the named assumption `linux_netz_binden_vertrag` (falsifier sonde_netz_binden): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)fd;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)adresse;
    register uint64_t _sys_rdx __asm__("rdx") = (uint64_t)laenge;
    register int64_t _sys_rax __asm__("rax") = (int64_t)49u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi), "r" (_sys_rdx)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_netz_binden_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 9) {
            *_grund = NetzFehler_SchlechterFd;
            return false;
        }
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 13) {
            *_grund = NetzFehler_KeinZugriff;
            return false;
        }
        if (_sys_errno == 12) {
            *_grund = NetzFehler_KeinSpeicher;
            return false;
        }
        if (_sys_errno == 4) {
            *_grund = NetzFehler_Unterbrochen;
            return false;
        }
        if (_sys_errno == 11) {
            *_grund = NetzFehler_Wiederholen;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_netz_binden_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_netz_senden(void) {
    return true;
}

static bool roh_senden(uint64_t fd, uint64_t nachricht, uint64_t laenge, uint64_t zeichen, uint64_t ziel, uint64_t ziel_laenge, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_senden -- number 44 in rax; fd in rdi, nachricht in rsi, laenge in rdx, zeichen in r10, ziel in r8, ziel_laenge in r9.
     * The kernel behind this stub is the named assumption `linux_netz_senden_vertrag` (falsifier sonde_netz_senden): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)fd;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)nachricht;
    register uint64_t _sys_rdx __asm__("rdx") = (uint64_t)laenge;
    register uint64_t _sys_r10 __asm__("r10") = (uint64_t)zeichen;
    register uint64_t _sys_r8 __asm__("r8") = (uint64_t)ziel;
    register uint64_t _sys_r9 __asm__("r9") = (uint64_t)ziel_laenge;
    register int64_t _sys_rax __asm__("rax") = (int64_t)44u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi), "r" (_sys_rdx), "r" (_sys_r10), "r" (_sys_r8), "r" (_sys_r9)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_netz_senden_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 4) {
            *_grund = NetzFehler_Unterbrochen;
            return false;
        }
        if (_sys_errno == 11) {
            *_grund = NetzFehler_Wiederholen;
            return false;
        }
        if (_sys_errno == 105) {
            *_grund = NetzFehler_PaketeVerloren;
            return false;
        }
        if (_sys_errno == 9) {
            *_grund = NetzFehler_SchlechterFd;
            return false;
        }
        if (_sys_errno == 14) {
            *_grund = NetzFehler_FehlerAdresse;
            return false;
        }
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 12) {
            *_grund = NetzFehler_KeinSpeicher;
            return false;
        }
        if (_sys_errno == 13) {
            *_grund = NetzFehler_KeinZugriff;
            return false;
        }
        if (_sys_errno == 32) {
            *_grund = NetzFehler_LeitungWeg;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_netz_senden_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_netz_empfangen(void) {
    return true;
}

static bool roh_empfangen(uint64_t fd, uint64_t puffer, uint64_t laenge, uint64_t zeichen, uint64_t quelle, uint64_t quell_laenge, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_empfangen -- number 45 in rax; fd in rdi, puffer in rsi, laenge in rdx, zeichen in r10, quelle in r8, quell_laenge in r9.
     * The kernel behind this stub is the named assumption `linux_netz_empfangen_vertrag` (falsifier sonde_netz_empfangen): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)fd;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)puffer;
    register uint64_t _sys_rdx __asm__("rdx") = (uint64_t)laenge;
    register uint64_t _sys_r10 __asm__("r10") = (uint64_t)zeichen;
    register uint64_t _sys_r8 __asm__("r8") = (uint64_t)quelle;
    register uint64_t _sys_r9 __asm__("r9") = (uint64_t)quell_laenge;
    register int64_t _sys_rax __asm__("rax") = (int64_t)45u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi), "r" (_sys_rdx), "r" (_sys_r10), "r" (_sys_r8), "r" (_sys_r9)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_netz_empfangen_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 4) {
            *_grund = NetzFehler_Unterbrochen;
            return false;
        }
        if (_sys_errno == 11) {
            *_grund = NetzFehler_Wiederholen;
            return false;
        }
        if (_sys_errno == 105) {
            *_grund = NetzFehler_PaketeVerloren;
            return false;
        }
        if (_sys_errno == 9) {
            *_grund = NetzFehler_SchlechterFd;
            return false;
        }
        if (_sys_errno == 14) {
            *_grund = NetzFehler_FehlerAdresse;
            return false;
        }
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 12) {
            *_grund = NetzFehler_KeinSpeicher;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_netz_empfangen_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_speicher_karte(void) {
    return true;
}

static bool roh_karte(uint64_t adresse, uint64_t laenge, uint64_t schutz, uint64_t zeichen, uint64_t fd, uint64_t versatz, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_karte -- number 9 in rax; adresse in rdi, laenge in rsi, schutz in rdx, zeichen in r10, fd in r8, versatz in r9.
     * The kernel behind this stub is the named assumption `linux_speicher_karte_vertrag` (falsifier sonde_speicher_karte): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)adresse;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)laenge;
    register uint64_t _sys_rdx __asm__("rdx") = (uint64_t)schutz;
    register uint64_t _sys_r10 __asm__("r10") = (uint64_t)zeichen;
    register uint64_t _sys_r8 __asm__("r8") = (uint64_t)fd;
    register uint64_t _sys_r9 __asm__("r9") = (uint64_t)versatz;
    register int64_t _sys_rax __asm__("rax") = (int64_t)9u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi), "r" (_sys_rdx), "r" (_sys_r10), "r" (_sys_r8), "r" (_sys_r9)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_speicher_karte_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 12) {
            *_grund = NetzFehler_KeinSpeicher;
            return false;
        }
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 9) {
            *_grund = NetzFehler_SchlechterFd;
            return false;
        }
        if (_sys_errno == 13) {
            *_grund = NetzFehler_KeinZugriff;
            return false;
        }
        if (_sys_errno == 11) {
            *_grund = NetzFehler_Wiederholen;
            return false;
        }
        if (_sys_errno == 1) {
            *_grund = NetzFehler_Verboten;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_speicher_karte_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_faden_start(void) {
    return true;
}

static bool roh_klonen(uint64_t kind, uint64_t stapel, uint64_t eltern, uint64_t kindspeicher, uint64_t tls, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_klonen -- number 56 in rax; kind in rdi, stapel in rsi, eltern in rdx, kindspeicher in r10, tls in r8.
     * The kernel behind this stub is the named assumption `linux_faden_start_vertrag` (falsifier sonde_faden_start): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)kind;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)stapel;
    register uint64_t _sys_rdx __asm__("rdx") = (uint64_t)eltern;
    register uint64_t _sys_r10 __asm__("r10") = (uint64_t)kindspeicher;
    register uint64_t _sys_r8 __asm__("r8") = (uint64_t)tls;
    register int64_t _sys_rax __asm__("rax") = (int64_t)56u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi), "r" (_sys_rdx), "r" (_sys_r10), "r" (_sys_r8)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_faden_start_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 11) {
            *_grund = NetzFehler_Wiederholen;
            return false;
        }
        if (_sys_errno == 12) {
            *_grund = NetzFehler_KeinSpeicher;
            return false;
        }
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 1) {
            *_grund = NetzFehler_Verboten;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_faden_start_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_sperre(void) {
    return true;
}

static bool roh_warten(uint64_t adresse, uint64_t vorgang, uint64_t wert, uint64_t frist, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_warten -- number 202 in rax; adresse in rdi, vorgang in rsi, wert in rdx, frist in r10.
     * The kernel behind this stub is the named assumption `linux_sperre_vertrag` (falsifier sonde_sperre): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)adresse;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)vorgang;
    register uint64_t _sys_rdx __asm__("rdx") = (uint64_t)wert;
    register uint64_t _sys_r10 __asm__("r10") = (uint64_t)frist;
    register int64_t _sys_rax __asm__("rax") = (int64_t)202u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi), "r" (_sys_rdx), "r" (_sys_r10)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_sperre_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 4) {
            *_grund = NetzFehler_Unterbrochen;
            return false;
        }
        if (_sys_errno == 11) {
            *_grund = NetzFehler_Wiederholen;
            return false;
        }
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 14) {
            *_grund = NetzFehler_FehlerAdresse;
            return false;
        }
        if (_sys_errno == 110) {
            *_grund = NetzFehler_ZeitUm;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_sperre_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_zeit_lesen(void) {
    return true;
}

static bool roh_uhr(uint64_t uhr, uint64_t adresse, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_uhr -- number 228 in rax; uhr in rdi, adresse in rsi.
     * The kernel behind this stub is the named assumption `linux_zeit_lesen_vertrag` (falsifier sonde_zeit_lesen): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)uhr;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)adresse;
    register int64_t _sys_rax __asm__("rax") = (int64_t)228u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_zeit_lesen_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 14) {
            *_grund = NetzFehler_FehlerAdresse;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_zeit_lesen_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_anhalten(void) {
    return true;
}

static bool roh_ende(uint64_t status, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_ende -- number 231 in rax; status in rdi.
     * The kernel behind this stub is the named assumption `linux_anhalten_vertrag` (falsifier sonde_anhalten): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)status;
    register int64_t _sys_rax __asm__("rax") = (int64_t)231u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_anhalten_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 4) {
            *_grund = NetzFehler_Unterbrochen;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_anhalten_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

static bool sonde_bericht_schreiben(void) {
    return true;
}

static bool roh_schreiben(uint64_t fd, uint64_t puffer, uint64_t laenge, uint64_t *_wert, NetzFehler *_grund) {
    /* syscall roh_schreiben -- number 1 in rax; fd in rdi, puffer in rsi, laenge in rdx.
     * The kernel behind this stub is the named assumption `linux_bericht_schreiben_vertrag` (falsifier sonde_bericht_schreiben): that it answers inside its
     * contract is assumed, and the decoding below is generated from the
     * declared `errors` map, exhaustively. */
    register uint64_t _sys_rdi __asm__("rdi") = (uint64_t)fd;
    register uint64_t _sys_rsi __asm__("rsi") = (uint64_t)puffer;
    register uint64_t _sys_rdx __asm__("rdx") = (uint64_t)laenge;
    register int64_t _sys_rax __asm__("rax") = (int64_t)1u;
    __asm__ __volatile__(
        "syscall\n"
        : "+a" (_sys_rax)
        : "r" (_sys_rdi), "r" (_sys_rsi), "r" (_sys_rdx)
        : "rcx", "r11", "memory");
    if (_sys_rax < 0) {
        if (_sys_rax < -4095) {
        /* `hardware (linux_bericht_schreiben_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
        }
        int64_t _sys_errno = -_sys_rax;
        if (_sys_errno == 4) {
            *_grund = NetzFehler_Unterbrochen;
            return false;
        }
        if (_sys_errno == 11) {
            *_grund = NetzFehler_Wiederholen;
            return false;
        }
        if (_sys_errno == 9) {
            *_grund = NetzFehler_SchlechterFd;
            return false;
        }
        if (_sys_errno == 14) {
            *_grund = NetzFehler_FehlerAdresse;
            return false;
        }
        if (_sys_errno == 22) {
            *_grund = NetzFehler_FalscherWert;
            return false;
        }
        if (_sys_errno == 12) {
            *_grund = NetzFehler_KeinSpeicher;
            return false;
        }
        if (_sys_errno == 32) {
            *_grund = NetzFehler_LeitungWeg;
            return false;
        }
        /* An errno the `errors` map does not admit. */
        /* `hardware (linux_bericht_schreiben_vertrag)` -- the kernel answered outside its contract.
         * Under the named assumption this point is not reached; that decision is
         * handed to the C compiler, which decides nothing of its own. */
        #if defined(__GNUC__)
        __builtin_unreachable();
        #endif
    }
    *_wert = (uint64_t)_sys_rax;
    return true;
}

uint64_t netz_socket(void) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_socket(AF_NETLINKE, SOCK_ROH, NETLINKE_FILTER, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t netz_binden(uint64_t fd, uint64_t adresse, uint64_t laenge) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_binden(fd, adresse, laenge, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t netz_senden(uint64_t fd, uint64_t nachricht, uint64_t laenge, uint64_t zeichen, uint64_t ziel, uint64_t ziel_laenge) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_senden(fd, nachricht, laenge, zeichen, ziel, ziel_laenge, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t netz_empfangen(uint64_t fd, uint64_t puffer, uint64_t laenge, uint64_t zeichen, uint64_t quelle, uint64_t quell_laenge) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_empfangen(fd, puffer, laenge, zeichen, quelle, quell_laenge, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t speicher_karte(uint64_t laenge) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_karte(0, laenge, KARTE_SCHUTZ, KARTE_ZEICHEN, KEIN_WERT, 0, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t faden_start(uint64_t kind, uint64_t stapel, uint64_t eltern, uint64_t kindspeicher, uint64_t tls) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_klonen(kind, stapel, eltern, kindspeicher, tls, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t sperre_warten(uint64_t adresse, uint64_t wert) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_warten(adresse, FUTEX_WARTEN, wert, 0, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t sperre_wecken(uint64_t adresse, uint64_t anzahl) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_warten(adresse, FUTEX_WECKEN, anzahl, 0, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t zeit_lesen(uint64_t uhr, uint64_t adresse) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_uhr(uhr, adresse, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t anhalten(uint64_t status) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_ende(status, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return status;
            } break;
            case NetzFehler_Wiederholen: {
                return status;
            } break;
            case NetzFehler_KeinSpeicher: {
                return status;
            } break;
            case NetzFehler_PaketeVerloren: {
                return status;
            } break;
            case NetzFehler_FalscherWert: {
                return status;
            } break;
            case NetzFehler_SchlechterFd: {
                return status;
            } break;
            case NetzFehler_FehlerAdresse: {
                return status;
            } break;
            case NetzFehler_FamilieFehlt: {
                return status;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return status;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return status;
            } break;
            case NetzFehler_SystemVoll: {
                return status;
            } break;
            case NetzFehler_Verboten: {
                return status;
            } break;
            case NetzFehler_KeinZugriff: {
                return status;
            } break;
            case NetzFehler_ZeitUm: {
                return status;
            } break;
            case NetzFehler_LeitungWeg: {
                return status;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}

uint64_t bericht_schreiben(uint64_t adresse, uint64_t laenge) {
    uint64_t v;
    {
        NetzFehler e;
        if (!roh_schreiben(FEHLER_AUSGABE, adresse, laenge, &v, &e)) {
            switch (e) {
            case NetzFehler_Unterbrochen: {
                return NOCHMAL;
            } break;
            case NetzFehler_Wiederholen: {
                return NOCHMAL;
            } break;
            case NetzFehler_KeinSpeicher: {
                return KEIN_WERT;
            } break;
            case NetzFehler_PaketeVerloren: {
                return PAKETE_VERLOREN;
            } break;
            case NetzFehler_FalscherWert: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SchlechterFd: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FehlerAdresse: {
                return KEIN_WERT;
            } break;
            case NetzFehler_FamilieFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ProtokollFehlt: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZuVieleDateien: {
                return KEIN_WERT;
            } break;
            case NetzFehler_SystemVoll: {
                return KEIN_WERT;
            } break;
            case NetzFehler_Verboten: {
                return KEIN_WERT;
            } break;
            case NetzFehler_KeinZugriff: {
                return KEIN_WERT;
            } break;
            case NetzFehler_ZeitUm: {
                return KEIN_WERT;
            } break;
            case NetzFehler_LeitungWeg: {
                return KEIN_WERT;
            } break;
            }
            #if defined(__GNUC__)
            __builtin_unreachable();
            #endif
        }
    }
    return v;
}
